FROM centos:7

ENV LANG en_US.utf8

COPY Centos-7.repo /etc/yum.repos.d/CentOS-Base.repo
COPY epel-7.repo /etc/yum.repos.d/epel.repo

RUN yum update -y && yum install -y fontconfig vim htop net-tools telnet nmap lsof wget && yum clean all && yum makecache

COPY .vimrc /root/.vimrc