FROM ubuntu:18.04

ENV LANG C.UTF-8
COPY sources-18.04.list /etc/apt/sources.list
RUN apt update && apt install -y vim htop iputils-ping net-tools telnet nmap lsof curl wget
RUN apt install -y openjdk-11-jdk

COPY .vimrc /root/.vimrc