FROM ubuntu:16.04

RUN apt update && apt install -y software-properties-common
COPY sources-16.04.list /etc/apt/sources.list
RUN add-apt-repository ppa:openjdk-r/ppa
RUN apt update && apt install -y openjdk-11-jdk
