FROM ubuntu:14.04

RUN apt update && apt install -y apt-transport-https software-properties-common
COPY sources-14.04.list /etc/apt/sources.list
RUN add-apt-repository ppa:openjdk-r/ppa
RUN apt update && apt install -y openjdk-8-jre
