FROM ubuntu:14.04

ENV LANG C.UTF-8

RUN apt update && apt install -y apt-transport-https software-properties-common
RUN add-apt-repository ppa:openjdk-r/ppa
RUN apt update && apt install -y openjdk-11-jre
COPY sources-14.04.list /etc/apt/sources.list
